---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
    
- name: "set environment variables"
  ansible.builtin.shell: |
       export ENVIRONMENT=production
       export TYPEORM_CONNECTION=postgres
       export TYPEORM_ENTITIES="./src/modules/domain/**/*.entity.ts"
       export TYPEORM_HOST="udapeople-prod.ckoqs4dqnyzx.us-east-2.rds.amazonaws.com"
       export TYPEORM_PORT="5432"
       export TYPEORM_USERNAME=postgres
       export TYPEORM_PASSWORD=udapeople123
       export TYPEORM_DATABASE=udapeople-prod
  become: yes