---
- name: "Copy files"
  become: yes
  unarchive:
   src: /root/project/backend.tar.gz
   dest: /home/ubuntu

- name: "Install NPM packages"
  shell: |
    cd ~/backend
    sudo npm install

- name: "Start Server"
  shell: |
    cd ~/backend
    pm2 start npm --name backend -- start